version: "3.8"

services:
  db:
    image: mysql:latest
    restart: unless-stopped
    ports: 
      - "3008:3306"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

    environment:
      MYSQL_ROOT_PASSWORD: 7618
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 7618
    volumes:
      - db-volume:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  
  
# api:
#   build: ./app
#   restart: unless-stopped
#   depends_on:
#     - db
#   ports:
#     - "8000:80"
#   environment:
#     DB_HOST: db
#     DB_PORT: 3306
#     DB_USER: user
#     DB_PASSWORD: 7618
#     DB_NAME: db


      
volumes:
  db-volume: